### PR TITLE
Added the option to test mail

### PR DESCRIPTION
**Pull request by tsfoni**
From now, you can send a test mail!

### CODE REVIEW

**Comment by tsfoni** [comment]
One more thing, I would like to contact you. Therefore, Please tell me how I can reach you.

Best Regards, 
Harel Tsfoni

**Comment by Cloud9Developer** [comment]
Discord would be the best bet!
Cloud9_Development#0181

**Review by Cloud9Developer — COMMENTED** [review]
Moving forward, could you submit PRs to the 'development' branch? Want to try and keep master as current release code

**Review by Cloud9Developer — APPROVED** [review]
For the life of me, I could not get that to work.. when I tried Thanks!!

**Pull request merged**
